# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 21:23
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations

from corehq.sql_db.operations import RawSQLMigration, HqRunSQL

migrator = RawSQLMigration(('corehq', 'sql_proxy_accessors', 'sql_templates'), {
    'PL_PROXY_CLUSTER_NAME': settings.PL_PROXY_CLUSTER_NAME
})


class Migration(migrations.Migration):

    dependencies = [
        ('sql_proxy_accessors', '0038_drop_unused_sql'),
    ]

    operations = [
        migrator.get_migration('get_reverse_indexed_cases_2.sql'),
    ]
